Repository atomist/atomist-sdm, pull requests merged in 2018-08, with the labels that each got.

#28 Dockerfile autofix fix
  Dockerfile
  package-lock.json
  package.json
  src/autofix/addHeader.ts
  src/autofix/license/thirdPartyLicense.ts
  src/autofix/npm/dockerfileFix.ts
  test/autofix/license/thirdPartyLicenseTest.ts
  test/autofix/npm/dockerfileFixTest.ts
  tsconfig.json
  tslint.json
Labels: atomist:merge-on-approve

#30 Support for releasing M and RC releases from a tag
  Dockerfile
  legal/THIRD_PARTY.md
  package-lock.json
  package.json
  src/machine/release.ts
  test/machine/releaseTest.ts
Labels: atomist:merge-on-approve, changelog:added

#37 Do not put a header before a shebang line
  Dockerfile
  src/autofix/addHeader.ts
  test/autofix/addHeaderTest.ts
Labels: changelog:fixed

#41 Add support for SDM local mode
  Dockerfile
  package-lock.json
  package.json
  src/atomist.config.ts
  src/autofix/license/thirdPartyLicense.ts
  src/machine/goals.ts
  src/machine/machine.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#42 Add code transforms for Atomist peer dependencies and package.json author
  src/machine/nodeSupport.ts
  src/machine/tryToUpdateAtomistPeerDependencies.ts
  src/machine/updatePackageAuthor.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added
