Repository atomist/atomist-sdm, pull requests merged in 2018-09, with the labels that each got.

#52 Add fingerprint support for npm
  package-lock.json
  package.json
  src/machine/machine.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#53 Autofix: tslint
  package-lock.json
  package.json
  src/machine/goals.ts
Labels: auto-merge-method:squash, auto-merge:on-approve

#64 Choose to raise a PR on the current project for a library version update
  package-lock.json
  package.json
Labels: auto-merge:on-check-success

#65 Move to projectListeners for nom install, version and compile
  Dockerfile
  lib/atomist.config.ts
  lib/autofix/license/thirdPartyLicense.ts
  lib/machine/goals.ts
  lib/machine/nodeSupport.ts
  lib/support/nodeCompileProjectListener.ts
  lib/support/nodeModulesProjectListener.ts
  lib/support/nodeVersionProjectListener.ts
  package-lock.json
  package.json
  test/autofix/license/thirdPartyLicense.test.ts
Labels: changelog:changed
