Repository atomist/atomist-sdm, pull requests merged in 2018-07, with the labels that each got.

#22 Breakout changelog support into extension pack
  legal/THIRD_PARTY.md
  package-lock.json
  package.json
  src/editing/changelog/changelog.ts
  src/editing/changelog/changelogParser.js
  src/graphql/subscription/closedIssueWithChangelogLabel.graphql
  src/graphql/subscription/closedPullRequestWithChangelogLabel.graphql
  src/handler/command/changelogLabels.ts
  src/handler/event/updateChangelog.ts
  src/machine/goals.ts
  src/machine/machine.ts
  src/machine/nodeSupport.ts
  src/machine/release.ts
  src/support/gitHubApi.ts
  src/support/messages.ts
  test/editing/changelog/changelogTest.ts
  test/machine/releaseTest.ts
  tsconfig.json
Labels: atomist:merge-on-approve, changelog:changed

#24 Fix non-client release builds, harmonize goals
  src/machine/goals.ts
Labels: changelog:fixed, enhancement

#26 Making sure the developer tutorials get built
  src/support/materialChangeToNodeRepo.ts
Labels: changelog:added
